# Generated by Django 3.2 on 2025-07-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
        ('bugs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_app.project'),
        ),
    ]
